---

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install Ruby development dependencies
  apt: pkg={{ item }}
  with_items: ruby_apt_dependencies

- name: Ensure Ruby build directory is present
  file: state=directory path={{ ruby_temp_directory }}

- name: Download Ruby source package
  get_url: url={{ ruby_source_url }}
           dest={{ ruby_temp_directory }}/{{ ruby_name }}.tar.gz
           sha256sum={{ ruby_source_checksum }}

- name: Extract Ruby source code
  command: tar -xf ruby-{{ ruby_version }}.tar.gz
           chdir={{ ruby_temp_directory }}
           creates={{ ruby_source_directory }}

- name: Configure Ruby compilation
  command: ./configure --prefix={{ ruby_install_directory }} --disable-install-doc
           chdir={{ ruby_source_directory }}
           creates={{ ruby_source_directory }}/Makefile

- name: Compile Ruby
  command: make
           chdir={{ ruby_source_directory }}
           creates={{ ruby_source_directory }}/ruby

- name: Check installed version of ruby
  command: "{{ ruby_install_directory }}/bin/ruby -v"
  register: installed_ruby_version
  failed_when: False
  changed_when: False

- name: Check compiled version of ruby
  command: "{{ ruby_source_directory }}/ruby -v"
  register: compiled_ruby_version
  failed_when: False
  changed_when: False

- name: Install Ruby
  command: make install
           chdir={{ ruby_source_directory }}
  when: compiled_ruby_version.rc == 0 and (installed_ruby_version.rc != 0 or installed_ruby_version.stdout != compiled_ruby_version.stdout)

- name: Check if Bundler is installed
  command: "{{ ruby_install_directory }}/bin/gem list bundler"
  changed_when: False
  register: bundler_installed

- name: Install Bundler
  command: "{{ ruby_install_directory }}/bin/gem install bundler --no-ri --no-rdoc"
  when: bundler_installed.stdout.find('bundler') == -1

- name: Create symlinks
  file: path=/usr/local/bin/{{ item }}
        src={{ ruby_install_directory }}/bin/{{ item }}
        state=link
  with_items:
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ri
    - ruby
    - testrb
    - bundle